import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Home2", href: "/" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={cn(inter.className, "min-h-dvh")}>
        <header className=" bg-red-600 container h-16 flex items-center justify-between">
          <div className="">mini-game</div>
          <ul className="flex items-center gap-4">
            {navItems.map((item) => (
              <li key={item.label}>
                <Button variant={"ghost"} asChild>
                  <Link href={item.href}>{item.label}</Link>
                </Button>
              </li>
            ))}
          </ul>
        </header>
        {children}
        <footer className="container h-16 bg-red-700 flex items-center top-full sticky">
          <div>&copy;y045u</div>
        </footer>
      </body>
    </html>
  );
}
