import Hero from "./components/hero";
import Features from "./components/features";
import Contact from "./components/contact";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "サービスについて",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <div className="">
      <Hero />
      <Features />
      <Contact />
    </div>
  );
}
